function MissionContent() {
  this.missionChoices = {
    en: missionChoices,
    ru: ruMissionChoices,
    fr: frMissionChoices,
    pl: plMissionChoices,
    deu: deuMissionChoices,
    it: itMissionChoices,
    es: esMissionChoices,
    ptp: ptpMissionChoices,
    ptb: ptbMissionChoices,
    tr: trMissionChoices,
    id: idMissionChoices,
    ja: jaMissionChoices,
  };

  this.missionPossibilities = senseLang;
}

module.exports = { MissionContent };

const missionChoices = [
  { name: "None (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Basic Mission", value: "bas" },
  { name: "Bayonet", value: "bay" },
  { name: "Breach", value: "bre" },
  { name: "Cleanup", value: "cle" },
  { name: "Common Only", value: "com" },
  { name: "Cover", value: "cov" },
  { name: "Hammer", value: "ham" },
  { name: "HILDR", value: "hildr" },
  { name: "Knife", value: "kni" },
  { name: "Locals", value: "loc" },
  { name: "Logistics", value: "log" },
  { name: "Rare Only", value: "rar" },
  { name: "Recon", value: "rec" },
  { name: "Showdown", value: "sho" },
  { name: "Uncommon Only", value: "unc" },
];
const ruMissionChoices = [
  { name: "Пусто (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "HILDR", value: "hildr" },
  { name: "Базовое Задание", value: "bas" },
  { name: "Доставка", value: "log" },
  { name: "Зачистка", value: "cle" },
  { name: "Местные", value: "loc" },
  { name: "Молот", value: "ham" },
  { name: "Нож", value: "kni" },
  { name: "Прикрытие", value: "cov" },
  { name: "Разборка", value: "sho" },
  { name: "Разведка", value: "rec" },
  { name: "Только Необычные", value: "unc" },
  { name: "Только Обычные", value: "com" },
  { name: "Только Редкие", value: "rar" },
  { name: "Штурм", value: "bre" },
  { name: "Штык", value: "bay" },
];
const frMissionChoices = [
  { name: "Rien (Default)", value: "null" },
  { name: "Affrontement", value: "sho" },
  { name: "B.S.S.", value: "bss" },
  { name: "Baionnette", value: "bay" },
  { name: "Breche", value: "bre" },
  { name: "Commun Uniquement", value: "com" },
  { name: "Couteau", value: "kni" },
  { name: "Couverture", value: "cov" },
  { name: "Frequent Uniquement", value: "unc" },
  { name: "HILDR", value: "hildr" },
  { name: "Locaux", value: "loc" },
  { name: "Logistique", value: "log" },
  { name: "Marteau", value: "ham" },
  { name: "Mission De Base", value: "bas" },
  { name: "Nettoyage", value: "cle" },
  { name: "Rare Uniquement", value: "rar" },
  { name: "Reconnaissance", value: "rec" },
];
const plMissionChoices = [
  { name: "Żaden (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Bagnet", value: "bay" },
  { name: "HILDR", value: "hildr" },
  { name: "Konfrontacja", value: "sho" },
  { name: "Logistyka", value: "log" },
  { name: "Miejscowi", value: "loc" },
  { name: "Mlot", value: "ham" },
  { name: "Noz", value: "kni" },
  { name: "Ochrona", value: "cov" },
  { name: "Oczyszczanie", value: "cle" },
  { name: "Rozpoznanie", value: "rec" },
  { name: "Szturm", value: "bre" },
  { name: "Tylko Niepospolite", value: "unc" },
  { name: "Tylko Pospolite", value: "com" },
  { name: "Tylko Rzadkie", value: "rar" },
  { name: "Zwykla Misja", value: "bas" },
];
const deuMissionChoices = [
  { name: "Keiner (Default)", value: "null" },
  { name: "Aufklarung", value: "rec" },
  { name: "Aufraumen", value: "cle" },
  { name: "B.S.S.", value: "bss" },
  { name: "Bayonett", value: "bay" },
  { name: "Deckung", value: "cov" },
  { name: "Durchbrechen", value: "bre" },
  { name: "Einfache Mission", value: "bas" },
  { name: "Hammer", value: "ham" },
  { name: "HILDR", value: "hildr" },
  { name: "Konfrontation", value: "sho" },
  { name: "Logistik", value: "log" },
  { name: "Lokal", value: "loc" },
  { name: "Messer", value: "kni" },
  { name: "Nur Gewohnl", value: "com" },
  { name: "Nur Selten", value: "rar" },
  { name: "Nur Ungewohnl", value: "unc" },
];
const itMissionChoices = [
  { name: "Niente (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Baionetta", value: "bay" },
  { name: "Breccia", value: "bre" },
  { name: "Coltello", value: "kni" },
  { name: "Copertura", value: "cov" },
  { name: "HILDR", value: "hildr" },
  { name: "Locali", value: "loc" },
  { name: "Logistica", value: "log" },
  { name: "Martello", value: "ham" },
  { name: "Missione Di Base", value: "bas" },
  { name: "Pulizia", value: "cle" },
  { name: "Ricognizione", value: "rec" },
  { name: "Scontro Finale", value: "sho" },
  { name: "Solo Comune", value: "com" },
  { name: "Solo Non Comune", value: "unc" },
  { name: "Solo Raro", value: "rar" },
];
const esMissionChoices = [
  { name: "Nada (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Bayoneta", value: "bay" },
  { name: "Cobertura", value: "cov" },
  { name: "Confrontacion", value: "sho" },
  { name: "Cuchillo", value: "kni" },
  { name: "HILDR", value: "hildr" },
  { name: "Infraccion", value: "bre" },
  { name: "Limpieza", value: "cle" },
  { name: "Logistica", value: "log" },
  { name: "Lugarenos", value: "loc" },
  { name: "Martillo", value: "ham" },
  { name: "Mision Basica", value: "bas" },
  { name: "Reconocimiento", value: "rec" },
  { name: "Solo Comunes", value: "com" },
  { name: "Solo Poco Comunes", value: "unc" },
  { name: "Solo Raros", value: "rar" },
];
const ptpMissionChoices = [
  { name: "Nada (Default)", value: "null" },
  { name: "Abrigar", value: "cov" },
  { name: "Apenas Comum", value: "com" },
  { name: "Apenas Incomum", value: "unc" },
  { name: "Apenas Raro", value: "rar" },
  { name: "B.S.S.", value: "bss" },
  { name: "Baioneta", value: "bay" },
  { name: "Duelo", value: "sho" },
  { name: "Faca", value: "kni" },
  { name: "HILDR", value: "hildr" },
  { name: "Limpeza", value: "cle" },
  { name: "Locais", value: "loc" },
  { name: "Logistica", value: "log" },
  { name: "Martelo", value: "ham" },
  { name: "Missao Basica", value: "bas" },
  { name: "Reconhecimento", value: "rec" },
  { name: "Romper", value: "bre" },
];
const ptbMissionChoices = [
  { name: "Nada (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Baioneta", value: "bay" },
  { name: "Brecha", value: "bre" },
  { name: "Cobertura", value: "cov" },
  { name: "Demonstracao", value: "sho" },
  { name: "Faca", value: "kni" },
  { name: "Habitantes", value: "loc" },
  { name: "HILDR", value: "hildr" },
  { name: "Limpeza", value: "cle" },
  { name: "Logistica", value: "log" },
  { name: "Martelo", value: "ham" },
  { name: "Missao Basica", value: "bas" },
  { name: "Reconhecimento", value: "rec" },
  { name: "Somente Comum", value: "com" },
  { name: "Somente Incomum", value: "unc" },
  { name: "Somente Raro", value: "rar" },
];
const trMissionChoices = [
  { name: "Yok (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Bicak", value: "kni" },
  { name: "Catisma", value: "sho" },
  { name: "Cekic", value: "log" },
  { name: "Gedik", value: "bre" },
  { name: "HILDR", value: "hildr" },
  { name: "Kesif", value: "rec" },
  { name: "Lojistik", value: "log" },
  { name: "Siper", value: "cov" },
  { name: "Sungu", value: "bay" },
  { name: "Tasfiye", value: "cle" },
  { name: "Temel Gorev", value: "bas" },
  { name: "Yalnizca Nadir", value: "rar" },
  { name: "Yalnizca Sira Disi", value: "unc" },
  { name: "Yalnizca Yaygin", value: "com" },
  { name: "Yerel Ayarlar", value: "loc" },
];
const idMissionChoices = [
  { name: "Tidak Ada (Default)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "Bayonet", value: "bay" },
  { name: "Bentrok", value: "sho" },
  { name: "Bersihkan", value: "cle" },
  { name: "HILDR", value: "hildr" },
  { name: "Khusus Biasa", value: "com" },
  { name: "Khusus Langka", value: "rar" },
  { name: "Khusus Tidak Biasa", value: "unc" },
  { name: "Lindungi", value: "cov" },
  { name: "Logistik", value: "log" },
  { name: "Lokal", value: "loc" },
  { name: "Martil", value: "ham" },
  { name: "Misi Standar", value: "bas" },
  { name: "Pisau", value: "kni" },
  { name: "Recon", value: "rec" },
  { name: "Terobos", value: "bre" },
];

const jaMissionChoices = [
  { name: "なし (デフォルト)", value: "null" },
  { name: "B.S.S.", value: "bss" },
  { name: "基本ミッション", value: "bas" },
  { name: "銃剣", value: "bay" },
  { name: "侵入", value: "bre" },
  { name: "清掃", value: "cle" },
  { name: "コモンのみ", value: "com" },
  { name: "援護", value: "cov" },
  { name: "ハンマー", value: "ham" },
  { name: "HILDR", value: "hildr" },
  { name: "ナイフ", value: "kni" },
  { name: "ローカル", value: "loc" },
  { name: "物流", value: "log" },
  { name: "レアのみ", value: "rar" },
  { name: "偵察", value: "rec" },
  { name: "対決", value: "sho" },
  { name: "アンコモンのみ", value: "unc" },
];

/*
  const allLangContent = {
    en:{name:"generate",description:"Generate mission instructions for Tacticool",mis:"Mission",choices:missionChoices,format:"format",fDesc:"Set output format.",image:"Image (Default)",text:"Text",sText:"Split Text",l:"languages",lDesc:"Set output language(s). Valid options: en ru fr pl deu it es ptp ptb tr id"},
    ru:{name:"generate-ru",description:"Создание инструкций по миссии для Tacticool",mis:"Задание",choices:ruMissionChoices,format:"формат",fDesc:"Установите выходной формат.",image:"Картина (Default)",text:"Текст",sText:"Разделенный Текст",l:"языки",lDesc:"Установите язык(и) вывода. Допустимые врянты: en ru fr pl deu it es ptp ptb tr id"},
    fr:{name:"generate-fr",description:"Générer des instructions de mission pour Tacticool",mis:"Mission",choices:frMissionChoices,format:"format",fDesc:"Définissez le format de sortie.",image:"Photo (Default)",text:"Texte",sText:"Texte Fractionné",l:"langages",lDesc:"Définissez langue(s) de sortie. Options valides: en ru fr pl deu it es ptp ptb tr id"},
    pl:{name:"generate-pl",description:"Wygeneruj instrukcje misji dla Tacticool",mis:"Misji",choices:plMissionChoices,format:"format",fDesc:"Ustaw format wyjściowy.",image:"Obrazek (Default)",text:"Tekst",sText:"Podzielony Tekst",l:"języki",lDesc:"Ustaw języki wyjściowe. Prawidłowe opcje: en ru fr pl deu it es ptp ptb tr id"},
    deu:{name:"generate-deu",description:"Generieren Sie Missionsanweisungen für Tacticool",mis:"Mission",choices:deuMissionChoices,format:"format",fDesc:"Ausgabeformat einstellen.",image:"Bild (Default)",text:"Text",sText:"Geteilter Text",l:"sprachen",lDesc:"Stellen Sie die Ausgabesprache(n) ein. Gültige Optionen: en ru fr pl deu it es ptp ptb tr id"},
    it:{name:"generate-it",description:"Genera istruzioni di missione per Tacticool",mis:"Missione",choices:itMissionChoices,format:"formato",fDesc:"Imposta il formato di output.",image:"Immagine (Default)",text:"Testo",sText:"Testo Diviso",l:"lingue",lDesc:"Imposta le lingue di output. Opzioni valide: en ru fr pl deu es ptp ptb tr id"},
    es:{name:"generate-es",description:"Generar instrucciones de misión para Tacticool",mis:"Misión",choices:esMissionChoices,format:"formato",fDesc:"Establecer formato de salida.",image:"Imagen (Default)",text:"Texto",sText:"Texto Dividido",l:"idiomas",lDesc:"Establecer idioma(s) de salida. Opciones válidas: en ru fr pl deu it es ptp ptb tr id"},
    ptp:{name:"generate-ptp",description:"Gerar instruções de missão para Tacticool",mis:"Missão",choices:ptpMissionChoices,format:"formato",fDesc:"Defina o formato de saída.",image:"Foto (Default)",text:"Texto",sText:"Texto Dividido",l:"línguas",lDesc:"Defina idioma(s) de saída. Opções válidas: en ru fr pl deu it es ptp ptb tr id"},
    ptb:{name:"generate-ptb",description:"Gerar instruções de missão para Tacticool",mis:"Missão",choices:ptbMissionChoices,format:"formato",fDesc:"Defina o formato de saída.",image:"Foto (Default)",text:"Texto",sText:"Texto Dividido",l:"línguas",lDesc:"Defina idioma(s) de saída. Opções válidas: en ru fr pl deu it es ptp ptb tr id"},
    tr:{name:"generate-tr",description:"Tacticool için görev talimatları oluşturun",mis:"Misyon",choices:trMissionChoices,format:"biçim",fDesc:"Çıktı formatını ayarlayın.",image:"Resim (Default)",text:"Metin",sText:"Bölünmüş Metin",l:"diller",lDesc:"Çıkış dillerini ayarlayın. Geçerli seçenekler: en ru fr pl deu it es ptp ptb tr id"},
    id:{name:"generate-id",description:"Buat instruksi misi untuk Tacticool",mis:"Misi",choices:idMissionChoices,format:"format",fDesc:"Atur format keluaran.",image:"Gambar (Default)",text:"Teks",sText:"Teks Terpisah",l:"bahasa",lDesc:"Atur bahasa keluaran. Opsi yang valid: en ru fr pl deu it es ptp ptb tr id"},
  }
  */

const senseLang = {
  sho: [
    "showdown",
    "sho",
    "show",
    "shw",
    "разборка",
    "разб",
    "affrontement",
    "aff",
    "konfrontacja",
    "kon",
    "konf",
    "konfrontation",
    "kon",
    "konf",
    "scontro",
    "sco",
    "confrontacion",
    "con",
    "conf",
    "duelo",
    "due",
    "demonstracao",
    "dem",
    "catisma",
    "cat",
    "bentrok",
    "ben",
    "対決",
    "対",
  ], //["showdown","разборка","affrontement","konfrontacja",'konfrontation',"scontro","confrontacion","duelo","demonstracao","catisma","bentrok"],
  log: [
    "logistics",
    "log",
    "доставка",
    "дос",
    "logistique",
    "log",
    "logistyka",
    "log",
    "logistik",
    "log",
    "logistica",
    "log",
    "logistica",
    "log",
    "logistica",
    "log",
    "logistica",
    "log",
    "lojistik",
    "loj",
    "logistik",
    "log",
    "物流",
    "物",
  ], //["logistics","доставка","logistique","logistyka",'logistik',"logistica","logistica","logistica","logistica","lojistik","logistik"],
  ham: [
    "hammer",
    "ham",
    "молот",
    "мол",
    "marteau",
    "mar",
    "mlot",
    "mlo",
    "hammer",
    "ham",
    "martello",
    "mar",
    "martillo",
    "mar",
    "martelo",
    "mar",
    "martelo",
    "mar",
    "cekic",
    "cek",
    "martil",
    "mar",
    "ハンマー",
    "ハ",
  ], //["hammer","молот","marteau","mlot",'hammer',"martello","martillo","martelo","martelo","cekic","martil"],
  bas: [
    "basic",
    "bas",
    "базовое",
    "баз",
    "base",
    "bas",
    "zwykla",
    "zwy",
    "einfache",
    "ein",
    "base",
    "bas",
    "basica",
    "bas",
    "basica",
    "bas",
    "basica",
    "bas",
    "temel",
    "tem",
    "standar",
    "sta",
    "基本",
    "基",
  ], //["basic mission","базовое","base","zwykla",'einfache',"base","basica","basica","basica","temel","standar"],
  bss: ["b.s.s.", "bss", "b.s.s"],
  cle: [
    "cleanup",
    "cle",
    "зачистка",
    "зач",
    "nettoyage",
    "net",
    "oczyszczanie",
    "ocz",
    "aufraumen",
    "aufr",
    "pulizia",
    "pul",
    "limpieza",
    "lim",
    "limpeza",
    "lim",
    "limpeza",
    "lim",
    "tasfiye",
    "tas",
    "bersihkan",
    "ber",
    "清掃",
    "清",
  ], //["cleanup","зачистка","nettoyage","oczyszczanie",'aufraumen',"pulizia","limpieza","limpeza","limpeza","tasfiye","bersihkan"],
  kni: [
    "knife",
    "kni",
    "нож",
    "couteau",
    "cout",
    "noz",
    "messer",
    "mes",
    "coltello",
    "col",
    "cuchillo",
    "cuc",
    "faca",
    "fac",
    "faca",
    "fac",
    "bicak",
    "bic",
    "pisau",
    "pis",
    "ナイフ",
    "ナ",
  ], //["knife","нож","couteau","noz",'messer',"coltello","cuchillo","faca","faca","bicak","pisau"],
  loc: [
    "locals",
    "loc",
    "местные",
    "мес",
    "locaux",
    "loc",
    "miejscowi",
    "mie",
    "lokal",
    "lok",
    "locali",
    "lugarenos",
    "lug",
    "locais",
    "habitantes",
    "hab",
    "yerel",
    "yer",
    "lokal",
    "ローカル",
    "ロ",
  ], //["locals","местные","locaux","miejscowi",'lokal',"locali","lugarenos","locais","habitantes","yerel ayarlar","lokal"],
  rec: [
    "recon",
    "rec",
    "разведка",
    "разв",
    "reconnaissance",
    "rozpoznanie",
    "roz",
    "aufklarung",
    "aufk",
    "ricognizione",
    "ric",
    "reconocimiento",
    "reconhecimento",
    "rec",
    "reconhecimento",
    "kesif",
    "kes",
    "偵察",
    "偵",
  ], //["recon","разведка","reconnaissance","rozpoznanie",'aufklarung',"ricognizione","reconocimiento","reconhecimento","reconhecimento","kesif","recon"],
  hildr: ["hil", "hildr"],
  rar: [
    "rare",
    "rar",
    "редкие",
    "ред",
    "rare",
    "rar",
    "rzadkie",
    "rza",
    "selten",
    "sel",
    "raro",
    "rar",
    "raros",
    "rar",
    "raro",
    "rar",
    "raro",
    "rar",
    "nadir",
    "nad",
    "langka",
    "lan",
    "レア",
    "レ",
  ], //["rare","редкие","rare","rzadkie",'selten',"raro","raros","raro","raro","nadir","langka"],
  bay: [
    "bayonet",
    "bay",
    "штык",
    "шты",
    "baionnette",
    "bai",
    "bagnet",
    "bag",
    "bayonett",
    "bay",
    "baionetta",
    "bai",
    "bayoneta",
    "bay",
    "baioneta",
    "bai",
    "baioneta",
    "bai",
    "sungu",
    "sun",
    "銃剣",
    "銃",
  ], //["bayonet","штык","baionnette","bagnet",'bayonett',"baionetta","bayoneta","baioneta","baioneta","sungu","bayonet"],
  com: [
    "common",
    "com",
    "обычные",
    "обы",
    "commun",
    "com",
    "pospolite",
    "pos",
    "gewohnl",
    "gew",
    "comune",
    "com",
    "comunes",
    "com",
    "comum",
    "com",
    "comum",
    "com",
    "yaygin",
    "yay",
    "biasa",
    "bia",
    "コモン",
    "コ",
  ], //["common","обычные","commun","pospolite","gewohnl","comune","comunes","comum","comum","yaygin","biasa"],
  unc: [
    "uncommon",
    "unc",
    "необычные",
    "нео",
    "frequent",
    "fre",
    "niepospolite",
    "nie",
    "ungewohnl",
    "ung",
    "noncomune",
    "nco",
    "pococomunes",
    "pco",
    "incomum",
    "inc",
    "incomum",
    "inc",
    "sira",
    "sir",
    "tidakbiasa",
    "tbi",
    "アンコモン",
    "アン",
    "ア",
  ], //["uncommon","необычные","frequent","niepospolite",'ungewohnl',"non comune","poco comunes","incomum","incomum","sira disi","tidak biasa"],
  cov: [
    "cover",
    "cov",
    "прикрытие",
    "при",
    "couverture",
    "couv",
    "ochrona",
    "och",
    "deckung",
    "dec",
    "copertura",
    "cop",
    "cobertura",
    "cob",
    "abrigar",
    "abr",
    "cobertura",
    "cob",
    "siper",
    "sip",
    "lindungi",
    "lin",
    "援護",
    "援",
  ], //["cover","прикрытие","couverture","ochrona",'deckung',"copertura","cobertura","abrigar","cobertura","siper","lindungi"],
  bre: [
    "breach",
    "bre",
    "штурм",
    "шту",
    "breche",
    "bre",
    "szturm",
    "szt",
    "durchbrechen",
    "dur",
    "breccia",
    "bre",
    "infraccion",
    "inf",
    "romper",
    "rom",
    "brecha",
    "bre",
    "gedik",
    "ged",
    "terobos",
    "ter",
    "侵入",
    "侵",
  ], //["BREACH","ШТУРМ","BRECHE","SZTURM",'DURCHBRECHEN',"BRECCIA","INFRACCION","ROMPER","BRECHA","GEDIK","TEROBOS"],
};
